// Generated by gencpp from file comm/Comm.msg
// DO NOT EDIT!


#ifndef COMM_MESSAGE_COMM_H
#define COMM_MESSAGE_COMM_H

#include <ros/service_traits.h>


#include <comm/CommRequest.h>
#include <comm/CommResponse.h>


namespace comm
{

struct Comm
{

typedef CommRequest Request;
typedef CommResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Comm
} // namespace comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm::Comm > {
  static const char* value()
  {
    return "0fa1ccfd0a5a431161710f45bbf0130a";
  }

  static const char* value(const ::comm::Comm&) { return value(); }
};

template<>
struct DataType< ::comm::Comm > {
  static const char* value()
  {
    return "comm/Comm";
  }

  static const char* value(const ::comm::Comm&) { return value(); }
};


// service_traits::MD5Sum< ::comm::CommRequest> should match 
// service_traits::MD5Sum< ::comm::Comm > 
template<>
struct MD5Sum< ::comm::CommRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm::Comm >::value();
  }
  static const char* value(const ::comm::CommRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm::CommRequest> should match 
// service_traits::DataType< ::comm::Comm > 
template<>
struct DataType< ::comm::CommRequest>
{
  static const char* value()
  {
    return DataType< ::comm::Comm >::value();
  }
  static const char* value(const ::comm::CommRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm::CommResponse> should match 
// service_traits::MD5Sum< ::comm::Comm > 
template<>
struct MD5Sum< ::comm::CommResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm::Comm >::value();
  }
  static const char* value(const ::comm::CommResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm::CommResponse> should match 
// service_traits::DataType< ::comm::Comm > 
template<>
struct DataType< ::comm::CommResponse>
{
  static const char* value()
  {
    return DataType< ::comm::Comm >::value();
  }
  static const char* value(const ::comm::CommResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_MESSAGE_COMM_H
