// Generated by gencpp from file comm/CommRequest.msg
// DO NOT EDIT!


#ifndef COMM_MESSAGE_COMMREQUEST_H
#define COMM_MESSAGE_COMMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm
{
template <class ContainerAllocator>
struct CommRequest_
{
  typedef CommRequest_<ContainerAllocator> Type;

  CommRequest_()
    : command(0)  {
    }
  CommRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int8_t _command_type;
  _command_type command;




  typedef boost::shared_ptr< ::comm::CommRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm::CommRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CommRequest_

typedef ::comm::CommRequest_<std::allocator<void> > CommRequest;

typedef boost::shared_ptr< ::comm::CommRequest > CommRequestPtr;
typedef boost::shared_ptr< ::comm::CommRequest const> CommRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm::CommRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm::CommRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::comm::CommRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm::CommRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm::CommRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm::CommRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm::CommRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm::CommRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm::CommRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "481ac5a494c3140a2539020bd74c82c7";
  }

  static const char* value(const ::comm::CommRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x481ac5a494c3140aULL;
  static const uint64_t static_value2 = 0x2539020bd74c82c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm::CommRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm/CommRequest";
  }

  static const char* value(const ::comm::CommRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm::CommRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 command\n\
";
  }

  static const char* value(const ::comm::CommRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm::CommRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm::CommRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm::CommRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MESSAGE_COMMREQUEST_H
